### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by JWCook** [shintoo/darwin#14]
Hi there, I don't have a problem or question, but wanted to say this looks like a super cool project!

It's also worth mentioning there are some other developers of "fanmade" iNaturalist-related projects who hang out on the Discord server here: https://discord.gg/uskv2yx It might be worth showing off Darwin there, maybe in the 'research and tech' channel, and also on the [iNat forums](https://forum.inaturalist.org) if you haven't already.

There's also this server, mainly for chat about development of an iNat Discord bot, but also stuff about the iNat API in general: https://discord.gg/pUbZFDbDdD I think a couple others there also work with the eBird API.

**Comment by shintoo** [comment]
Thanks; and thanks for the invite, will check it out :cowboy_hat_face:
